version: "3.8"
services:
  backend:
    build:
      context: .
    image: ashrapov/user-manager:latest
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT:-9200}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-elasticsearch}
    ports:
      - "${USER_APP_PORT:-7777}:7777"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"